name: Publish to npm and GitHub Packages

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          scope: '@dhvcc'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish to npmjs
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public

      - name: Publish to GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.REGISTRY_GITHUB_TOKEN }}
        run: |
          npm config set @dhvcc:registry https://npm.pkg.github.com/
          npm publish
